### PR TITLE
Fix pos_stats extraction

### LINKED ISSUE #74: `extract_df` not working for pos_stats in v 1.1.0
`extract_df` does not extract POS metrics, due to mismatch between metric name `pos_stats` and `Extractor.unpack_extension` logic, which checks for the original component name `pos_proportions` in spaCy.

### PR DESCRIPTION
**Pull request by rbroc**
closes #74 

Log:
- map `pos_stats` -> `pos_proportions` in `__unpack_extensions`, and adapt conditional logic accordingly
- fix and simplify iterative metric extraction in Extractor init method (all metrics which do not throw an error should work with `__unpack_extension`)

### CODE REVIEW

**Comment by HLasse** [comment]
Thanks a lot for the PR, Roberta! 🙌

**Comment by HLasse** [comment]
@rbroc can I get you to update the minor version in the `about.py` file? I don't have access to make changes to your branch :)

**Comment by rbroc** [comment]
updated patch as per slack conversation ;)

**Comment by HLasse** [comment]
Amazing, thanks! Merging it in

**Pull request merged**
