### PR TITLE
Fix docstrings example module import error & Add doctrings missing imports

### PR DESCRIPTION
**Pull request by sondalex**
This PR fixed two documentation issues:

1) #338 
2) #339

### CODE REVIEW

**Review by KennethEnevoldsen — APPROVED** [review]
Thanks for these corrections. It generally looks good. @HLasse can't remember if the nlp pipes are needed for information_theory, but at least it is not needed for quality.

**Comment by HLasse** [comment]
Thanks, @sondalex! Re: information theory, I'll check it. Seems like a good time to fix the failing documentation CI workflow as well so we can get this merged.

**Comment by HLasse** [comment]
Thanks for your contribution, @sondalex! I have merged this PR into a branch with the CI fixes (#342 ) which will be merged now.

**Comment by sondalex** [comment]
Thank you for merging @HLasse !

**Pull request merged**
